version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # - run: sudo dpkg --purge --force-depends ca-certificates-java
      # - run: sudo apt-get install -qq ca-certificates-java
      - gradle/with_cache: 
          steps: 
            - run: ./gradlew clean
            - run: ./gradlew test
            - run: ./gradlew testUTF32

workflows:
  test:
    jobs:
      - test
        
